import "@/index.css";

import { useEffect, useMemo, useRef, useState } from "react";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import { useDisplayMode } from "skybridge/web";
import { Maximize2, Minimize2, Shuffle, User } from "lucide-react";
import { useToolInfo } from "./helpers.js";

const CANVAS_SIZE = 256;
const MIN_ZOOM = 1;
const MAX_ZOOM = 32;
const EMPTY_R = 240;
const EMPTY_G = 240;
const EMPTY_B = 240;

type WidgetMeta = {
  supabase: { url: string; anonKey: string };
  palette: string[];
};

type PixelRow = { x: number; y: number; color: number };

type DragStart = { mx: number; my: number; ox: number; oy: number };

function hexToRgb(hex: string): [number, number, number] {
  const m = hex.replace("#", "");
  return [
    parseInt(m.slice(0, 2), 16),
    parseInt(m.slice(2, 4), 16),
    parseInt(m.slice(4, 6), 16),
  ];
}

const NAME_STORAGE_KEY = "gptwar:user_name";
const NAME_ADJECTIVES = [
  "happy", "sleepy", "clever", "brave", "quiet", "witty", "rapid",
  "lucky", "keen", "jolly", "mellow", "fancy", "grumpy", "silly",
  "spicy", "cosmic", "plucky", "zesty", "glossy", "velvet",
];
const NAME_ANIMALS = [
  "fox", "otter", "koala", "panda", "tiger", "wolf", "heron",
  "badger", "raven", "lynx", "gecko", "newt", "sloth", "ferret",
  "gull", "puffin", "weasel", "stoat", "goose", "ibis",
];

function randomName(): string {
  const a = NAME_ADJECTIVES[Math.floor(Math.random() * NAME_ADJECTIVES.length)];
  const b = NAME_ANIMALS[Math.floor(Math.random() * NAME_ANIMALS.length)];
  const n = Math.floor(Math.random() * 100);
  return `${a}-${b}-${n}`;
}

function loadStoredName(): string | null {
  try {
    return window.localStorage.getItem(NAME_STORAGE_KEY);
  } catch {
    return null;
  }
}

function saveStoredName(name: string) {
  try {
    window.localStorage.setItem(NAME_STORAGE_KEY, name);
  } catch {
    /* ignore */
  }
}

export function CanvasWidget() {
  const info = useToolInfo<"canvas">();
  const meta = info.responseMetadata as unknown as WidgetMeta | undefined;
  const [displayMode, setDisplayMode] = useDisplayMode();
  const isFullscreen = displayMode === "fullscreen";

  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const outerRef = useRef<HTMLDivElement | null>(null);
  const pixelsRef = useRef<Int16Array>(
    new Int16Array(CANVAS_SIZE * CANVAS_SIZE).fill(-1),
  );
  // While the initial fetch is still running, realtime events are buffered
  // here (cell index → color). Replayed onto the fetched buffer at completion
  // so they aren't wiped.
  const fetchBufferRef = useRef<Map<number, number> | null>(null);
  const [live, setLive] = useState(false);
  const [placedCount, setPlacedCount] = useState(0);
  const [outerSize, setOuterSize] = useState({ w: 0, h: 0 });
  // Bumped whenever pixelsRef is bulk-replaced, triggering a full redraw.
  const [snapshotVersion, setSnapshotVersion] = useState(0);

  // Pan + zoom.
  const [zoom, setZoom] = useState(1);
  const [offset, setOffset] = useState({ x: 0, y: 0 });
  const [isDragging, setIsDragging] = useState(false);
  const dragStart = useRef<DragStart | null>(null);

  // User name. The first time the widget loads, prompt the user to pick a
  // name (autogenerated default). Persisted in localStorage. Surfaced to the
  // model via data-llm so it can pass it back as user_name on tool calls.
  const [userName, setUserName] = useState<string | null>(() => loadStoredName());
  const [nameModalOpen, setNameModalOpen] = useState<boolean>(
    () => loadStoredName() === null,
  );
  const [nameDraft, setNameDraft] = useState<string>(
    () => loadStoredName() ?? randomName(),
  );

  function confirmName() {
    const trimmed = nameDraft.trim().slice(0, 40);
    if (!trimmed) return;
    saveStoredName(trimmed);
    setUserName(trimmed);
    setNameModalOpen(false);
  }

  function openNameModal() {
    setNameDraft(userName ?? randomName());
    setNameModalOpen(true);
  }

  const paletteRgb = useMemo(
    () => (meta?.palette ?? []).map(hexToRgb),
    [meta?.palette],
  );
  const paletteRgbRef = useRef(paletteRgb);
  paletteRgbRef.current = paletteRgb;

  function drawAll() {
    const canvas = canvasRef.current;
    const pal = paletteRgbRef.current;
    if (!canvas || pal.length === 0) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;
    const img = ctx.createImageData(CANVAS_SIZE, CANVAS_SIZE);
    const pixels = pixelsRef.current;
    for (let i = 0; i < pixels.length; i++) {
      const c = pixels[i];
      const o = i * 4;
      if (c < 0) {
        img.data[o] = EMPTY_R;
        img.data[o + 1] = EMPTY_G;
        img.data[o + 2] = EMPTY_B;
        img.data[o + 3] = 255;
      } else {
        const rgb = pal[c] ?? [0, 0, 0];
        img.data[o] = rgb[0];
        img.data[o + 1] = rgb[1];
        img.data[o + 2] = rgb[2];
        img.data[o + 3] = 255;
      }
    }
    ctx.putImageData(img, 0, 0);
  }

  function drawOne(x: number, y: number, color: number) {
    const canvas = canvasRef.current;
    const pal = paletteRgbRef.current;
    if (!canvas || pal.length === 0) return;
    if (x < 0 || y < 0 || x >= CANVAS_SIZE || y >= CANVAS_SIZE) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;
    const rgb = pal[color] ?? [0, 0, 0];
    ctx.fillStyle = `rgb(${rgb[0]}, ${rgb[1]}, ${rgb[2]})`;
    ctx.fillRect(x, y, 1, 1);
  }

  // Measure outer — base scale = min(w,h) / CANVAS_SIZE at zoom=1.
  useEffect(() => {
    const el = outerRef.current;
    if (!el) return;
    const ro = new ResizeObserver((entries) => {
      const r = entries[0].contentRect;
      setOuterSize({ w: r.width, h: r.height });
    });
    ro.observe(el);
    return () => ro.disconnect();
  }, []);

  // Paginated fetch so we bypass PostgREST's default 1000-row cap.
  // Buffer realtime events during the fetch so they don't get wiped.
  useEffect(() => {
    if (!meta?.supabase?.url || !meta?.supabase?.anonKey) return;
    let cancelled = false;
    fetchBufferRef.current = new Map();
    const client = createClient(meta.supabase.url, meta.supabase.anonKey, {
      auth: { persistSession: false },
    });

    (async () => {
      const buf = new Int16Array(CANVAS_SIZE * CANVAS_SIZE).fill(-1);
      let count = 0;
      const pageSize = 1000;
      let from = 0;
      while (!cancelled) {
        const { data, error } = await client
          .from("pixels")
          .select("x, y, color")
          .range(from, from + pageSize - 1);
        if (cancelled) return;
        if (error) {
          console.warn("[canvas] fetch failed:", error);
          fetchBufferRef.current = null;
          return;
        }
        const rows = data ?? [];
        for (const row of rows) {
          buf[row.y * CANVAS_SIZE + row.x] = row.color;
          count++;
        }
        if (rows.length === 0 || rows.length < pageSize) break;
        from += pageSize;
      }
      if (cancelled) return;
      // Replay realtime events that landed during the fetch.
      const pending = fetchBufferRef.current;
      if (pending) {
        for (const [cell, color] of pending) {
          if (buf[cell] < 0 && color >= 0) count++;
          buf[cell] = color;
        }
      }
      fetchBufferRef.current = null;
      pixelsRef.current = buf;
      setPlacedCount(count);
      setSnapshotVersion((v) => v + 1);
    })();

    return () => {
      cancelled = true;
      fetchBufferRef.current = null;
    };
  }, [meta?.supabase?.url, meta?.supabase?.anonKey]);

  // biome-ignore lint/correctness/useExhaustiveDependencies: ignore
  useEffect(() => {
    drawAll();
  }, [snapshotVersion, paletteRgb]);

  // biome-ignore lint/correctness/useExhaustiveDependencies: ignore Realtime subscription — other clients' writes + our own confirmations.
  useEffect(() => {
    if (!meta?.supabase?.url || !meta?.supabase?.anonKey) return;
    const client: SupabaseClient = createClient(
      meta.supabase.url,
      meta.supabase.anonKey,
      {
        auth: { persistSession: false },
        realtime: { params: { eventsPerSecond: 30 } },
      },
    );
    const channel = client
      .channel("pixels-live")
      .on(
        "postgres_changes",
        { event: "*", schema: "public", table: "pixels" },
        (payload) => {
          const row = (payload.new ?? payload.old) as PixelRow | undefined;
          if (!row) return;
          const idx = row.y * CANVAS_SIZE + row.x;
          const prev = pixelsRef.current[idx];
          pixelsRef.current[idx] = row.color;
          // If a fetch is in flight, stash the event so it survives the
          // buffer replacement at fetch-completion.
          if (fetchBufferRef.current) {
            fetchBufferRef.current.set(idx, row.color);
          }
          if (prev < 0 && row.color >= 0) {
            setPlacedCount((n) => n + 1);
          }
          drawOne(row.x, row.y, row.color);
        },
      )
      .subscribe((status) => {
        setLive(status === "SUBSCRIBED");
      });
    return () => {
      client.removeChannel(channel);
    };
  }, [meta?.supabase?.url, meta?.supabase?.anonKey]);

  // Pan + zoom transforms.
  const baseScale =
    outerSize.w > 0 && outerSize.h > 0
      ? Math.min(outerSize.w, outerSize.h) / CANVAS_SIZE
      : 1;
  const totalScale = baseScale * zoom;
  const centerX = (outerSize.w - CANVAS_SIZE * totalScale) / 2;
  const centerY = (outerSize.h - CANVAS_SIZE * totalScale) / 2;

  const wheelStateRef = useRef({
    zoom,
    offset,
    outerSize,
    baseScale,
    centerX,
    centerY,
  });
  wheelStateRef.current = {
    zoom,
    offset,
    outerSize,
    baseScale,
    centerX,
    centerY,
  };

  useEffect(() => {
    const el = outerRef.current;
    if (!el) return;
    const handler = (e: WheelEvent) => {
      e.preventDefault();
      const s = wheelStateRef.current;
      if (s.outerSize.w === 0 || s.outerSize.h === 0) return;
      const rect = el.getBoundingClientRect();
      const mx = e.clientX - rect.left;
      const my = e.clientY - rect.top;
      let rawDelta = e.deltaY;
      if (e.deltaMode === 1) rawDelta *= 15;
      else if (e.deltaMode === 2) rawDelta *= 100;
      const clamped = Math.max(-80, Math.min(80, rawDelta));
      const factor = Math.exp(-clamped * 0.003);
      const newZoom = Math.max(MIN_ZOOM, Math.min(MAX_ZOOM, s.zoom * factor));
      if (newZoom === s.zoom) return;
      const currentTx = s.centerX + s.offset.x;
      const currentTy = s.centerY + s.offset.y;
      const newBase = s.baseScale * newZoom;
      const newCenterX = (s.outerSize.w - CANVAS_SIZE * newBase) / 2;
      const newCenterY = (s.outerSize.h - CANVAS_SIZE * newBase) / 2;
      const scaleRatio = newZoom / s.zoom;
      const newTx = mx - (mx - currentTx) * scaleRatio;
      const newTy = my - (my - currentTy) * scaleRatio;
      setZoom(newZoom);
      setOffset({ x: newTx - newCenterX, y: newTy - newCenterY });
    };
    el.addEventListener("wheel", handler, { passive: false });
    return () => el.removeEventListener("wheel", handler);
  }, []);

  function onPointerDown(e: React.PointerEvent<HTMLDivElement>) {
    if (e.button !== 0) return;
    e.currentTarget.setPointerCapture(e.pointerId);
    setIsDragging(true);
    dragStart.current = {
      mx: e.clientX,
      my: e.clientY,
      ox: offset.x,
      oy: offset.y,
    };
  }

  function onPointerMove(e: React.PointerEvent<HTMLDivElement>) {
    const start = dragStart.current;
    if (!isDragging || !start) return;
    setOffset({
      x: start.ox + (e.clientX - start.mx),
      y: start.oy + (e.clientY - start.my),
    });
  }

  function onPointerUp(e: React.PointerEvent<HTMLDivElement>) {
    e.currentTarget.releasePointerCapture?.(e.pointerId);
    setIsDragging(false);
    dragStart.current = null;
  }

  const tx = centerX + offset.x;
  const ty = centerY + offset.y;
  const measured = outerSize.w > 0 && outerSize.h > 0;
  const ready = !!meta && measured;

  return (
    <div
      className={`canvas-wrap ${isFullscreen ? "fullscreen" : ""}`}
      data-llm={`Pixel canvas ${CANVAS_SIZE}x${CANVAS_SIZE}, ${placedCount} pixels placed${live ? "" : " (connecting)"}.${userName ? ` The user's chosen name is "${userName}" — pass this as user_name on every place-pixels or stamp-grid call.` : ""} Use place-pixels or stamp-grid to draw.`}
    >
      <div
        ref={outerRef}
        className={`canvas-outer ${isDragging ? "dragging" : ""}`}
        onPointerDown={onPointerDown}
        onPointerMove={onPointerMove}
        onPointerUp={onPointerUp}
        onPointerCancel={onPointerUp}
      >
        <canvas
          ref={canvasRef}
          width={CANVAS_SIZE}
          height={CANVAS_SIZE}
          style={{
            position: "absolute",
            left: 0,
            top: 0,
            width: CANVAS_SIZE,
            height: CANVAS_SIZE,
            transform: `translate(${tx}px, ${ty}px) scale(${totalScale})`,
            transformOrigin: "0 0",
            opacity: ready ? 1 : 0,
          }}
        />
        <button
          type="button"
          className="canvas-icon-btn fullscreen-btn"
          aria-label={isFullscreen ? "Collapse" : "Fullscreen"}
          title={isFullscreen ? "Collapse" : "Fullscreen"}
          onClick={() =>
            setDisplayMode(isFullscreen ? "inline" : "fullscreen")
          }
        >
          {isFullscreen ? <Minimize2 size={16} /> : <Maximize2 size={16} />}
        </button>

        {userName && !nameModalOpen && (
          <button
            type="button"
            className="name-pill"
            aria-label="Change name"
            title="Change name"
            onClick={openNameModal}
          >
            <User size={14} />
            <span>{userName}</span>
          </button>
        )}
      </div>

      {nameModalOpen && (
        <div className="name-modal-backdrop">
          <form
            className="name-modal"
            onSubmit={(e) => {
              e.preventDefault();
              confirmName();
            }}
          >
            <h2 className="name-modal-title">Pick a name</h2>
            <p className="name-modal-sub">
              Shown next to the drawings you make and visible to the model.
            </p>
            <div className="name-modal-row">
              <input
                className="name-modal-input"
                autoFocus
                type="text"
                value={nameDraft}
                maxLength={40}
                onChange={(e) => setNameDraft(e.target.value)}
              />
              <button
                type="button"
                className="canvas-icon-btn name-shuffle"
                aria-label="Random name"
                title="Random name"
                onClick={() => setNameDraft(randomName())}
              >
                <Shuffle size={16} />
              </button>
            </div>
            <button
              type="submit"
              className="name-modal-confirm"
              disabled={!nameDraft.trim()}
            >
              Continue
            </button>
          </form>
        </div>
      )}
    </div>
  );
}
